name: Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
    - name: Make Docker image
      run: |
        docker build -t biosimulator-image .
    - name: Run Docker
      run: |
        docker run biosimulator-image
